In [15]:
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display, display_markdown

from src.news_scraper import create_session, fetch_yf_search_news, fetch_yf_ticker_news

In [2]:
session = create_session()
articles = fetch_yf_ticker_news(session, "AAPL")
print(len(articles))
for article in articles[:5]:
    print(f"{article.published} | {article.title}")
    print(f" {article.url}")

10
2026-02-08T21:43:49Z | Dow Jones Futures Due; Dow Tops 50K As Apple, Boeing, These AI Stocks Are Buys. But Market Is Still Divided.
 https://www.investors.com/market-trend/stock-market-today/dow-jones-50000-apple-boeing-jpmorgan-ai-stocks/?src=A00220&yptr=yahoo
2026-02-08T18:30:09Z | Apple (AAPL) Should Be Up Again, Says Jim Cramer
 https://finance.yahoo.com/news/apple-aapl-again-says-jim-183009101.html
2026-02-08T18:29:35Z | Qualcomm’s (QCOM) Hurt By Memory, Says Jim Cramer
 https://finance.yahoo.com/news/qualcomm-qcom-hurt-memory-says-182935774.html
2026-02-08T17:25:54Z | IVV’s Uninterrupted Dividend Streak Since 2000 Masks The True Income Profile
 https://247wallst.com/investing/2026/02/08/ivvs-uninterrupted-dividend-streak-since-2000-masks-the-true-income-profile/
2026-02-08T17:00:00Z | A Critical AI Niche Is Dominated by One Little-Known Japanese Company
 https://www.wsj.com/tech/a-critical-ai-niche-is-dominated-by-one-little-known-japanese-company-d9101853?siteid=yhoof2&yptr=yahoo

In [18]:
session = create_session()
articles = fetch_yf_search_news(session, "AI Investment")
print(len(articles))
for article in articles[:5]:
    print(f"{article.published} | {article.title}")
    print(f" {article.url}")
display(article.to_dict())

10
2026-02-08T20:13:00+00:00 | Ernst & Young drops a blunt reality check on the economy
 https://finance.yahoo.com/m/aa5f89aa-59b4-37ea-b55d-f464df355751/ernst-%26-young-drops-a-blunt.html
2026-02-08T19:13:00+00:00 | 2 Artificial Intelligence (AI) Stocks That Could Help Make You a Fortune
 https://finance.yahoo.com/m/8a1da167-af6d-3075-a424-999ad294f348/2-artificial-intelligence.html
2026-02-08T16:46:09+00:00 | Cathie Wood buys $43 million of megacap tech stock
 https://finance.yahoo.com/m/1bdb3135-7132-3fc3-8185-75725115b526/cathie-wood-buys-%2443-million.html
2026-02-08T16:04:52+00:00 | Microsoft’s AI Chip And Partnerships Tested By Recent Share Price Weakness
 https://finance.yahoo.com/news/microsoft-ai-chip-partnerships-tested-160452450.html
2026-02-08T16:00:03+00:00 | 'This probably seems overdone': Wall Street strategists weigh in on software stock sell-off
 https://finance.yahoo.com/news/this-probably-seems-overdone-wall-street-strategists-weigh-in-on-software-stock-sell-off-160003877.html

{'title': "'This probably seems overdone': Wall Street strategists weigh in on software stock sell-off",
 'url': 'https://finance.yahoo.com/news/this-probably-seems-overdone-wall-street-strategists-weigh-in-on-software-stock-sell-off-160003877.html',
 'published': '2026-02-08T16:00:03+00:00',
 'summary': '',
 'category': 'AI Investment',
 'source': 'yfinance_search',
 'content': '',
 'ticker': 'ANTH.PVT,GOOG,IVZ,^IXIC,CRM,NOW,AMZN,META,MSFT',
 'author': 'Yahoo Finance',
 'article_id': 'ba089452-e595-4c50-9f70-ba64e6351540',
 'metadata': {'type': 'STORY', 'query': 'AI Investment'}}

In [7]:
display(article.to_dict())

{'title': 'A Critical AI Niche Is Dominated by One Little-Known Japanese Company',
 'url': 'https://www.wsj.com/tech/a-critical-ai-niche-is-dominated-by-one-little-known-japanese-company-d9101853?siteid=yhoof2&yptr=yahoo',
 'published': '2026-02-08T17:00:00Z',
 'summary': 'The century-old former silk spinner pioneered a cloth-like material made from glass fibers. Now a shortage is looming over the artificial-intelligence boom.',
 'category': '',
 'source': 'yfinance_ticker',
 'content': '',
 'ticker': 'AAPL',
 'author': '',
 'article_id': '7275f224-ffbe-302d-8233-a3fb377ed8b4',
 'metadata': {'contentType': 'STORY',
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}}}}

In [8]:
from src.news_scraper import collect_financial_news

df = collect_financial_news(
    sources=["cnbc", "nasdaq"],
    tickers=["AAPL", "MSFT"],
)
print(f"収集: {len(df)}件")
print(df[["title", "source", "category"]].head())

収集: 346件
                                               title source category
0  Layoffs in January were the highest to start a...   cnbc  economy
1  China's Xi reasserts Taiwan stance in call wit...   cnbc  economy
2  January jobs report will be released on Feb. 1...   cnbc  economy
3  Private payrolls rose by just 22,000 in Januar...   cnbc  economy
4  Trump refuses to be outdone by Europe, signing...   cnbc  economy

In [9]:
display(df)

                                                 title  ... metadata
0    Layoffs in January were the highest to start a...  ...       {}
1    China's Xi reasserts Taiwan stance in call wit...  ...       {}
2    January jobs report will be released on Feb. 1...  ...       {}
3    Private payrolls rose by just 22,000 in Januar...  ...       {}
4    Trump refuses to be outdone by Europe, signing...  ...       {}
..                                                 ...  ...      ...
360  This Datacenter REIT Could Double as Hyperscal...  ...       {}
361    There's a Rout in Tech Stocks. What's Going On?  ...       {}
362      The Best Stocks to Invest $5,000 in Right Now  ...       {}
363  Why Some Analysts Believe Artificial Intellige...  ...       {}
364  2 Unstoppable Stocks That Can Be Great Options...  ...       {}

[346 rows x 11 columns]

In [12]:
display(df.loc[df['source']=='cnbc'])

                                                 title  ... metadata
0    Layoffs in January were the highest to start a...  ...       {}
1    China's Xi reasserts Taiwan stance in call wit...  ...       {}
2    January jobs report will be released on Feb. 1...  ...       {}
3    Private payrolls rose by just 22,000 in Januar...  ...       {}
4    Trump refuses to be outdone by Europe, signing...  ...       {}
..                                                 ...  ...      ...
235  Oil prices rise after Trump says a 'massive Ar...  ...       {}
236  This university campus is heated by an AI data...  ...       {}
237  How the USA Rare Earth deal with the Trump adm...  ...       {}
238  USA Rare Earth shares rally as Commerce Depart...  ...       {}
239  Natural gas prices hit $6 for first time since...  ...       {}

[221 rows x 11 columns]